file delete -force work
vlib  work
vmap  work
vlog -sv +incdir+./ ./DWC_pcie_ctl_cc_constants.svh
vlog -sv +incdir+./include ./include/pcie_defs.svh
vlog -sv +incdir+./include ./include/cxpl_defs.svh
vlog -sv +incdir+./include ./include/adm_defs.svh
vlog -sv +incdir+./include ./include/radm_defs.svh
vlog -sv +incdir+./include ./include/port_cfg.svh
vlog -sv +incdir+./include ./include/cap_port_cfg.svh
vlog -sv +incdir+./include ./include/pipe_defines.svh
vlog -sv +incdir+./include ./include/DWC_pcie_ctl_all_defs.svh
vlog -sv +incdir+./power_management ./power_management/DWC_pcie_pm_pkg.svh

vlog -sv +define+IPSL_PCIE_SPEEDUP_SIM +define+DWC_DISABLE_CDC_METHOD_REPORTING +define+IPML_HSST_SPEEDUP_SIM -override_timescale 1ns/10ps \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DW_sbc/DW_sbc_bound_init.svp            \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DW_sbc/DW_sbc.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/delay_n_w_stalling.svp                  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/ram_latency_pipe.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcm41.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcm48.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcmmod48.svp                   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/lcrc.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/lcrc_unit.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/lane_flip_mux.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/lane_flip.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/tb_lane_flip_mux.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/delay_n.svp                             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/delay_n_w_enable.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/lbc.svp                                 \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcm57.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcmmod57.svp                   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bvm02.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcm21.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcm22.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcm64_td.svp                   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcm65_td.svp                   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcmmod65_init_td.svp           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/DWC_pcie_bcm86.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/rxeidle_squelch.svp                     \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/delay_1_w_stalling.svp                  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/common/lcrc_einj.svp                           \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/rmlh.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/smlh_link.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/rmlh_deskew.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/rmlh_deskew_slv.svp                     \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/smlh_seq_finder.svp                     \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/smlh_seq_finder_slv.svp                 \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/rmlh_pkt_finder.svp                     \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/smlh_eidle_infer.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/scramble.svp                            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/scramble_slv.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/rmlh_pipe.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/rmlh_pipe_squelch.svp                   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/xmlh.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/smlh.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/smlh_ltssm.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/xmlh_pipe.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/xmlh_pat_gen.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/xmlh_byte_xmt.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/pipe_adapter.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/pipe_loopback.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer1/xmlh_smb_einj.svp                       \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/rdlh_link_cntrl.svp                     \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/rdlh_tlp_extract.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/rdlh_dlp_extract.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/rdlh.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/xdlh_tracker.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/xdlh_dllp_gen.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/xdlh_retrybuf.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/xdlh_detect_dllp.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/xdlh_control_64b.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/xdlh_tlp_gen_64b.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer2/xdlh_64b.svp                            \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/rtlh_fc_decode.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/rtlh_fc_gen.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/rtlh_fc_arb.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/rtlh_tlp_ecrc.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/rtlh_tlp_extract.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/rtlh_tlp_check_slv.svp                  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/rtlh_tlp_check.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/rtlh_fc.svp                             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/rtlh.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/xtlh_tracker.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/xtlh.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Layer3/xtlh_ctrl.svp                           \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_tracker.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_vc_fc.svp                             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_fc.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_arb.svp                               \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_mux.svp                               \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_hdr_form.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_cplq_mng.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_cplq_client.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_cplq_cnt.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_out_formation.svp                     \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_order_mgr.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_order_q.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_crd_return.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_inq_mgr.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_outq_mgr.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_outq_mgr_ctl.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_q_seg_buf.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_formation.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_idle_detect.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_clk_control.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_filter_rc.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_filter_ep.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_cpl_lut.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_cpl_filter.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_cpl_lut_vec_extractor.svp             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_qformation.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm.svp                                   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_dm.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/radm_state.svp                             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/DWC_pcie_rst_ctl.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Adm/xadm_tlp_einj.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_reg_decode.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_bar_match.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_cfg_reg.svp                            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_ecfg_reg.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_error_reg.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_pm_reg.svp                             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_msi_reg.svp                            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_tph_reg.svp                            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rbar_reg.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_trgt_map.svp                           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_pl_reg.svp                             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_msg_req.svp                            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_int_req.svp                            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/msg_arbitration.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/msg_formation.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/msg_gen.svp                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rasdes_cmn_reg.svp                     \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rasdes_ecnt.svp                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rasdes_ec_ramcont.svp                  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rasdes_ec_reg.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rasdes_einj_reg.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rasdes_ramif.svp                       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rasdes_reg.svp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rasdes_sd_reg.svp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm_rasdes_tba_reg.svp                     \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_active_ctrl_aux_timer.svp  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_lane_flip_ctrl.svp         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_cfg.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_cfg_pme.svp                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_wakeup.svp                 \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_flag.svp                   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pme_ctrl.svp                  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_active_flags.svp           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_timer.svp                  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_active_timer.svp           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_active_ctrl.svp            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/shadow_reg.svp                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/phy_if_cpcie_shadow.svp       \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/phy_if_cpcie_mux.svp          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/phy_if_cpcie.svp              \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/phy_mux.svp                   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_ctrl.svp                   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_shadow.svp                 \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_clk_control_fsm.svp        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_clk_control.svp            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/pm_rst_control.svp            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/DWC_pcie_pd_if.svp            \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/DWC_pcie_phystatus_fsm.svp    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/DWC_pcie_phystatus_sync.svp   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/DWC_pcie_phystatus_detect.svp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/power_management/DWC_pcie_phystatus_if.svp     \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/hot_plug_ctrl.svp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/Cdm/cdm.svp                                    \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/timers/DWC_pcie_tim_gen.svp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/timers/DWC_pcie_symbol_timer.svp               \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/customer/generic/ram_2p_sotbuf.vp              \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/customer/generic/ram_cdm_rasdes_reg.vp         \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/products/cx_pl.svp                             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/products/DWC_pcie_core.svp                     \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/DWC_pcie_ctl.svp                               \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_apper_adapter.vp                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_axis_master_adapter.vp          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_axis_slave_adapter.vp           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_cpltimeout_adapter.vp           \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_ctrl.vp                         \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_dbi_adapter.vp                  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_litein_adapter.vp               \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_liteout_adapter.vp              \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_master_adapter_fifo.vp          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_msi_adapter.vp                  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_pin_mux.vp                      \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_pipe_adapter.vp                 \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_pipe_adapter_rxstatus.vp        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_pulsein_adapter.vp              \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_pulseout_adapter.vp             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_reqack_adapter.vp               \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_slave_adapter_fifo.vp           \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_iip_rams.vp                          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_debug_adapter.vp                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_elbi_adapter.vp                 \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_elbi_cdc_adapter.vp             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_elbi_sp_adapter.vp              \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/top/pcie2_hard_ram2p.vp                        \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst.vp                    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst_bcm21.vp              \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst_bcm41.vp              \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst_bvm02.vp              \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst_clk_gater.vp          \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst_cpcie.vp              \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst_mux2.vp               \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst_sfsm.vp               \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst_sync.vp               \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/examples/DWC_pcie_clkrst_sync_reset.vp         \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/external_ram_test/pcie2_ram_hdr_data_mux.vp    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/external_ram_test/pcie2_ram_hdr_data_mux_dly.vp\
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/external_ram_test/pcie2_external_ram_test.vp   \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/external_ram_test/pcie2_reg6ram.vp             \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/external_ram_test/pcie2_external_ram_dpcmd.vp  \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/external_ram_test/pcie2_ram_mux_test_top.vp    \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/external_ram_test/pcie2_external_ram_spcmd.vp  \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/rtl/DWC_pcie_ctl-undef.vp                          \
                                                                                                \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/pciegen2_source_codes/PCIEGEN2.vp                                        \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/common_lib/*.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pgl_hsst.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pgl_hsst_top.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pgl_pcs.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pgl_pma.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pgl_tielo.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/s1007_serdes_io.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_txrx_interface.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_bist_chk.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_bist_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_chk_counter_8bit_adder.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_clk_blk.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_clk_sw.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_err_insertion.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_icg_high.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_mem_blk.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pma_data16bit_order_map_rx.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pma_data16bit_order_map_tx.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pma_data_retime.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_prbs_fb_matrix_15.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_prbs_fb_matrix_23.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_prbs_fb_matrix_31.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_prbs_fb_matrix_7.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_res_bias_calib.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_reset_sync.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_rx2tx_lpbk_fifo.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_rx_ctrl_logic.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_rx_data_polarity.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_rx_interface.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_rx_oob_detector.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_rx_sigdet_fsm.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_sync_clr.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_tx2rx_plpbk.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_tx_ctrl_logic.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_tx_fifo.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_tx_interface.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_tx_mode_transfer.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_tx_pdata_mux.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_txrx_clk_mux_2to1.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_rx_cdr_6g25.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_asyncfifo.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_fifomem.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_10bit_acc.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_11bit_acc.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_config.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_int_path.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_int_sat_det.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_phdet_adder.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_phdet_cell.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_phdet_stg1.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_phdet.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_pi_ctrl_decoder.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_prop_path.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_pseudo_lockdet.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_rx_pi_ctrl_acc.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_shifter.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pi_ctrl_fifo.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_reset_sync_cdr.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_rptr_empty.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_sync_r2w.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_sync_w2r.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_wptr_full.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_ctle_chan_est_element.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_ctle_chan_est.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_ctle_lock_detect.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_ctle_loop_filter.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_ctle_mux_sel.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_ctle_slicer.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_ctle_stg.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_ready_check.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_cdr_clk_mux_2to1.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_offset_stg.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_offset_chan.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_offset_chan_cell.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_offset_slicer.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_offset_loop_filter.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_offset_mux_sel.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pll_register_hw.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pll_ctrl_logic.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pll_fsm.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pll_lock_detect.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_rescal_ctrl.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_reset_sync_pll.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pll_rst_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pma6g_pll_clk_mux_2to1.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_a_detect_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/dqsl_ddr_dll_del_var.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_apb_config_pma_lane.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_apb_config_pma_quad.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_apb_config.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_apb_config_top.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_asyncfifo.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_bit_slip.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_bridge_reg.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_ceb_fifo.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_ce_bonding_top_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_clk_aligner.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_clk_mux_2to1.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_clk_mux_4to1.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_clk_pol_ctrl.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_comma_detect_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_comma_det_pattern.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_comma_det_sub.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_ctc_add_data_pro.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_ctc_afifo.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_ctc_del_data_pro.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_ctc_ge_auto_data.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_ctc_mcb_flag_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_ctc_unit_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_current_mux.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_data_mux_fty.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_data_mux_twty.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_decode_3b4b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_decode_5b6b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_decode_8b10b_dual.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_decode_8b10b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_delay.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_disp_check_dual.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_drive_reg.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_encoder_3b4b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_encoder_5b6b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_encoder_8b10b_dual.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_encoder_8b10b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_fifomem.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_tx_gear_box.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_tx_data_adaptor.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_invalid_code_check.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_invalid_k_detector.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_lsm_10gb_eth_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_lsm_10ge_ceb_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_lsm_1gb_eth_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_lsm_rapid_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_lsm_rapid_ceb_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_near_loop_enable.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_prbs_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rd_controller.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rd_reg.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rptr_empty.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rst_sync.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_bridge_unit.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_clk_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_clkrst_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_gear_box.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_data_adaptor.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_data_mux.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_gear_data_slip.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_prbs_data_width_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_rst_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rx_samp_reg.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_special_3b4b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_sync_r2w.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_sync_r2w_test.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_sync_w2r.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_sync_w2r_test.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/top_pcs_single.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/top_pcs.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_top_rx.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_top_tx.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_tx_bridge_unit.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_tx_clk_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_tx_clkrst_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_tx_rst_gen.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_wl_regd_r_clken.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_word_align_top_20b.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_wptr_full.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_pma_test_status_unit.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_asyncfifo_test.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_rptr_empty_test.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_wptr_full_test.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_bs_top.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_bs_receiver.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_bs_transmitter.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_asyncfifo_txbridge.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_fifomem_txbridge.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/hsst_e2_source_codes/pcs_reg_clkinv_clken.vp \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/GTP_HSST_E2.v \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/GTP_DRM18K.v \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/GTP_CLKBUFG.v \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/GTP_IOBUF.v \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/GTP_PCIEGEN2.v \
C:/pango/PDS_2022.1/ip/system_ip/ipsl_pcie/ipsl_pcie_eval/ipsl_pcie-1.3/../../../../../arch/vendor/pango/verilog/simulation/GTP_GRS.v \
-f ./pango_pcie_top_filelist.f -l vlog.log
vsim -novopt +define+IPSL_PCIE_SPEEDUP_SIM +define+DWC_DISABLE_CDC_METHOD_REPORTING +define+IPML_HSST_SPEEDUP_SIM work.pango_pcie_top_tb -l vsim.log
do pango_pcie_top_wave.do
run -all
