
set_property PACKAGE_PIN J14 [get_ports rgmii_rxc]
set_property PACKAGE_PIN F13 [get_ports rgmii_rx_ctl]
set_property PACKAGE_PIN H13 [get_ports rgmii_rxd[0]]
set_property PACKAGE_PIN H12 [get_ports rgmii_rxd[1]]
set_property PACKAGE_PIN D11 [get_ports rgmii_rxd[2]]
set_property PACKAGE_PIN E11 [get_ports rgmii_rxd[3]]
set_property PACKAGE_PIN G14 [get_ports rgmii_txc]
set_property PACKAGE_PIN D10 [get_ports rgmii_tx_ctl]
set_property PACKAGE_PIN J13 [get_ports rgmii_txd[0]]
set_property PACKAGE_PIN K13 [get_ports rgmii_txd[1]]
set_property PACKAGE_PIN E12 [get_ports rgmii_txd[2]]
set_property PACKAGE_PIN F12 [get_ports rgmii_txd[3]]

set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rxc]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rx_ctl]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rxd[0]]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rxd[1]]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rxd[2]]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rxd[3]]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_txc]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_tx_ctl]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_txd[0]]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_txd[1]]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_txd[2]]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_txd[3]]

set_property PACKAGE_PIN AC23 [get_ports clk_40m]
set_property IOSTANDARD LVCMOS33 [get_ports clk_40m]
set_property PACKAGE_PIN Y18 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property PACKAGE_PIN E13 [get_ports phy_rstn]
set_property IOSTANDARD LVCMOS18 [get_ports phy_rstn]
